"""Render the checksum manifest for every file deployed by fata-install.

This manifest detects an incomplete checkout or accidental local drift before
the installer writes into a home directory. It is not a signature: Git commit
verification and signed release tags remain the trust boundary for a clone.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "VERSION"
OUTPUT_FILE = ROOT / "assets" / "deployment.sha256"
DEPLOYMENT_PATTERNS = (
    "config/hypr/hyprland.lua",
    "config/hypr/hyprpaper.conf",
    "config/hypr/fata/*.lua",
    "config/kitty/kitty.conf",
    "config/kitty/fata/*.conf",
    "config/mako/config",
    "config/rofi/config.rasi",
    "config/rofi/fata.rasi",
    "config/rofi/fata/*.rasi",
    "config/waybar/config.*.jsonc",
    "config/waybar/style.css",
    "config/waybar/fata/*.css",
    "scripts/fata-rofi",
    "assets/art/fata-morgana/manifest.json",
    "assets/art/fata-morgana/*.jpg",
    "assets/wallpapers/fata-morgana/manifest.json",
    "assets/wallpapers/fata-morgana/*.jpg",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def release_version() -> str:
    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not version or any(character not in "0123456789." for character in version):
        raise RuntimeError("VERSION must contain a numeric dotted release version")
    return version


def deployment_paths() -> list[Path]:
    paths: set[Path] = set()
    for pattern in DEPLOYMENT_PATTERNS:
        matches = sorted(ROOT.glob(pattern))
        if not matches:
            raise RuntimeError(f"deployment pattern has no files: {pattern}")
        paths.update(matches)

    resolved_root = ROOT.resolve()
    for path in paths:
        if not path.is_file() or path.is_symlink():
            raise RuntimeError(f"deployment source must be a regular non-symlink file: {path}")
        try:
            path.resolve().relative_to(resolved_root)
        except ValueError as error:
            raise RuntimeError(f"deployment source escapes repository root: {path}") from error
    return sorted(paths, key=lambda path: path.relative_to(ROOT).as_posix())


def render() -> str:
    lines = [
        f"# Fata Morgana deployment manifest v{release_version()}",
        "# Generated by tools/build_release_manifest.py; paths are repository-relative.",
    ]
    for path in deployment_paths():
        relative = path.relative_to(ROOT).as_posix()
        lines.append(f"{sha256(path)}  {relative}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the tracked manifest differs from current sources")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT_FILE.is_file() or OUTPUT_FILE.read_text(encoding="utf-8") != expected:
            raise SystemExit("Release manifest: FAIL: assets/deployment.sha256 is out of date")
        print(f"Release manifest: verified {len(deployment_paths())} deployment files.")
        return 0
    # sha256sum parses the manifest as a byte-oriented POSIX text file. Force
    # LF even when the generator is run from a Windows checkout.
    with OUTPUT_FILE.open("w", encoding="utf-8", newline="\n") as output:
        output.write(expected)
    print(f"Release manifest: wrote {len(deployment_paths())} deployment files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
